### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'get_display_name'

### ISSUE THREAD

**Issue by schwos** [bb-Ricardo/netbox-sync#120] opened 2021-12-20 05:39 UTC
I was testing  this out and tried the main code then moved to development code and both resulted in the same error. It appears that it is looking for a object that doesn't exists in get tags section. We don't use tags much in our netbox dev site. Wanted to post this to see if you had a preferred way to address this?

It appears to happen when there is single tag associated with the item it is attempting to update. If I empty the tag it appears to move forward. You will see below the error the debug out put from the response body from netbox which has within the tags; color, dispaly, id, name, slug, etc. Now if I remove the nmap tag it will result in 'tags': [ ],

```
 Traceback (most recent call last):
   File "/opt/netbox-sync.py", line 145, in <module>
     main()
   File "/opt/netbox-sync.py", line 135, in main
     nb_handler.update_instance()
   File "/opt/module/netbox/connection.py", line 702, in update_instance
     self.update_object(nb_object_sub_class, unset=True)
   File "/opt/module/netbox/connection.py", line 588, in update_object
     self.update_object(dependency)
   File "/opt/module/netbox/connection.py", line 675, in update_object
     this_object.update(data=unresolved_dependency_data)
   File "/opt/module/netbox/object_classes.py", line 1546, in update
     super().update(data=data, read_from_netbox=read_from_netbox, source=source)
   File "/opt/module/netbox/object_classes.py", line 523, in update
     value = self.compile_tags(value)
   File "/opt/module/netbox/object_classes.py", line 803, in compile_tags
     current_tag_strings = self.get_tags()
   File "/opt/module/netbox/object_classes.py", line 757, in get_tags
     return [x.get_display_name() for x in self.data.get("tags", list())]
   File "/opt/module/netbox/object_classes.py", line 757, in <listcomp>
     return [x.get_display_name() for x in self.data.get("tags", list())]
 AttributeError: 'dict' object has no attribute 'get_display_name'
```
The Response Body:
```json
{
   "address":"192.168.1.1/24",
   "assigned_object":null,
   "assigned_object_id":null,
   "assigned_object_type":"virtualization.vminterface",
   "created":"2021-11-06",
   "custom_fields":{
      
   },
   "description":"labsrv02.local",
   "display":"192.168.1.1/24",
   "dns_name":"",
   "family":{
      "label":"IPv4",
      "value":4
   },
   "id":465,
   "last_updated":"2021-12-20T06:22:17.339660Z",
   "nat_inside":null,
   "nat_outside":null,
   "role":null,
   "status":{
      "label":"Active",
      "value":"active"
   },
   "tags":[
      {
         "color":"ffc107",
         "display":"nmap",
         "id":1,
         "name":"nmap",
         "slug":"nmap",
         "url":"http://netbox.local/api/extras/tags/1/"
      }
   ],
   "tenant":null,
   "url":"http://netbox.local/api/ipam/ip-addresses/465/",
   "vrf":null
}
```

**Comment by bb-Ricardo** [comment] 2021-12-20 08:02
Hi, this is not meant to happen. I will have a look in the next few days. I thought tags are a solved issue 🤷‍♂️.

Can you run the scriptwith -l DEBUG2 and add the last 20 lines befor it breaks?

Thank you.

**Comment by schwos** [comment] 2021-12-20 13:36
It isn't much different than what I already had provided with DEBUG3 but as you requested here is the results for DEBUG2. If I remove the single nmap tag it will not error out; but if there is any number of tags it will fail as below shows. I was digging through the code after this to see why it would; but started getting really late. I hope you have an idea; but I will continue to narrow down the focus if I can and provide any useful information I find. Thank You. 

2021-12-20 13:22:33,689 - DEBUG2: Received HTTP Status 200.
2021-12-20 13:22:33,689 - DEBUG2: Adding unresolved dependencies back to object: ['assigned_object_id', 'tags']
2021-12-20 13:22:33,689 - DEBUG2: Parsing 'IP address' data structure: 192.168.1.1/24
2021-12-20 13:22:33,690 - DEBUG2: Parsing 'tag' data structure: NetBox-synced
2021-12-20 13:22:33,690 - DEBUG2: Parsing 'tag' data structure: Source: my-vcenter-example
2021-12-20 13:22:33,690 - INFO: Ip address '192.168.1.1/24' attribute 'assigned_object_id' changed from 'None' to 'vNIC 1 (VM Network) (labsrv)'
2021-12-20 13:22:33,690 - INFO: Ip address '192.168.1.1/24' attribute 'tags' changed from '[]' to '['NetBox-synced', 'Source: my-vcenter-example']'
2021-12-20 13:22:33,690 - DEBUG: Updated IP address object: 192.168.1.1/24
2021-12-20 13:22:33,690 - INFO: Updating NetBox 'IP address' object '192.168.1.2/24' with data: {'assigned_object_type': 'virtualization.vminterface'}
2021-12-20 13:22:33,691 - DEBUG2: Sending PATCH to 'http://netbox.local:80/api/ipam/ip-addresses/464/' with data 'b'{"assigned_object_type": "virtualization.vminterface"}''.
2021-12-20 13:22:33,777 - DEBUG2: Received HTTP Status 200.
2021-12-20 13:22:33,777 - DEBUG2: Adding unresolved dependencies back to object: ['assigned_object_id', 'tags']
2021-12-20 13:22:33,777 - DEBUG2: Parsing 'IP address' data structure: 192.168.1.2/24
2021-12-20 13:22:33,777 - DEBUG2: Parsing 'tag' data structure: NetBox-synced
2021-12-20 13:22:33,777 - DEBUG2: Parsing 'tag' data structure: Source: my-vcenter-example
2021-12-20 13:22:33,778 - INFO: Ip address '192.168.1.2/24' attribute 'assigned_object_id' changed from 'None' to 'vNIC 1 (VM Network) (labsrv)'
2021-12-20 13:22:33,778 - INFO: Ip address '192.168.1.2/24' attribute 'tags' changed from '[]' to '['NetBox-synced', 'Source: my-vcenter-example']'
2021-12-20 13:22:33,778 - DEBUG: Updated IP address object: 192.168.1.2/24
2021-12-20 13:22:33,778 - INFO: Updating NetBox 'IP address' object '192.168.1.3/24' with data: {'assigned_object_type': 'virtualization.vminterface'}
2021-12-20 13:22:33,778 - DEBUG2: Sending PATCH to 'http://netbox.local:80/api/ipam/ip-addresses/465/' with data 'b'{"assigned_object_type": "virtualization.vminterface"}''.
2021-12-20 13:22:33,876 - DEBUG2: Received HTTP Status 200.
2021-12-20 13:22:33,876 - DEBUG2: Adding unresolved dependencies back to object: ['assigned_object_id', 'tags']
2021-12-20 13:22:33,876 - DEBUG2: Parsing 'IP address' data structure: 192.168.1.3/24
Traceback (most recent call last):
  File "/opt/netbox-sync.py", line 145, in <module>

**Comment by bb-Ricardo** [comment] 2021-12-20 14:27
mmhhh, wondering why the other tags (NetBox-synced, my-vcenter-example) were not added in the first place.

Do you have any other ERROR messages or WARNINGS in your log?

**Comment by schwos** [comment] 2021-12-20 16:36
No I would have included in logs for you and community to see if it did. The items above the failure did update in the Netbox journal entries. It is only when there is a tag associated with the object it will fail. Before walking away for a bit was trying to determine a way to drop the object into the logs so we could see what's in the object in the others and what's not before failure. It's obvious that it missing the object get_display_name which is odd if there is a tag.

**Comment by bb-Ricardo** [comment] 2021-12-20 16:41
For me it looks like an issue with the tag endpoint. Because the tags I mentioned before are anong the first items added to NetBox on a new installation. And your log excerpt tells me this didn't happen.

Which version of NetBox are you using?

Would it be possible to send me the whole log with `-l DEBUG2` to my email address (can be found at the top of betbox-sync.py)

That would be great. Thank you.

**Comment by schwos** [comment] 2021-12-20 16:45
The release just before the 3.1.1 release. I'm mobile at moment and confirm exact release this afternoon. 

I'm using the admin account token for this so it shouldn't be any access issues. 

Are we needing to add tags into the system prior to running the tool?

**Comment by bb-Ricardo** [comment] 2021-12-20 16:48
Ok, maybe something changed with 3.1

Will test it later on with a new version.

**Comment by schwos** [comment] 2021-12-20 17:12
I will email you as your asked when I get in front of system.

**Comment by schwos** [comment] 2021-12-20 19:15
Just sent email for your review

**Comment by bb-Ricardo** [comment] 2021-12-20 21:34
thank you very much, will have a look

**Comment by schwos** [comment] 2022-01-10 23:21
Did we  determine a resolution to this issue?

**Comment by pn-pn** [comment] 2022-01-20 14:41
Hi,

I'm experiencing the same issue. It appears that tags created manually on the Netbox instance are interpreted as simple dictionaries instead of NBTag objects and as a result don't have the `get_display_name()` method.

I've managed to create a simple workaround which transforms all tags into NBTag objects.

Here's the code of the modified `get_tags()` method which is located in `module/netbox/object_classes.py` (line 748):
```
    def get_tags(self):
        """
        returns a list of strings of tag names

        Returns
        -------
        list: of strings of tga names
        """
        try:
            # Try to execute the original code
            return [x.get_display_name() for x in self.data.get("tags", list())]
        except AttributeError:
            # If the error occurs, copy the data object
            data = dict(self.data).copy()
            # Initialize an empty list of tags
            tags = []
            # Iterate over all tags
            for tag in self.data.get("tags", list()):
                try:
                    # If a tag is not an NBTag object, it throws an AttributeError exception
                    tag.get_display_name()
                    # If an exception hasn't been thrown, it means the tag is correct
                    tags.append(tag)
                except AttributeError:
                    # Search for the NBTag object using the display name
                    o = self.inventory.get_by_data(NBTag, {"display": tag["display"]})
                    # If the object has been successfully found, it is appended to the list
                    if o:
                        tags.append(o)
                    # Otherwise log an error and make no changes
                    # This never happened in my case because all tags are correctly stored in the inventory
                    else:
                        log.error(f"Inventory returned None for {tag['display']}")
                        tags.append(tag)
            # Replace the tags
            data["tags"] = tags
            # Replace the data associated with the object
            self.data = data
        # Execute the original code
        return [x.get_display_name() for x in self.data.get("tags", list())]
```

Hope it helps.

**Comment by bb-Ricardo** [comment] 2022-01-20 14:58
Hey, thank you very much and good fimding. I have to check WHY they don't get parsed as NBTag object.

Had little time to fix things around here but will start again soon with a new version.

**Comment by bb-Ricardo** [comment] 2022-01-23 22:01
Hi,

I'm just sitting here and trying to reproduce the issue but I fail to do so. I really would like to find the root cause of "why are tags from NetBox are not parsed initially".

I spun up a new, empty instance and added tags. Also assigned tags to different objects but I never got this error.

Do you have an idea how to reproduce this error?

Thank you.

**Comment by schwos** [comment] 2022-01-23 23:15
you must have existing tags. 

Sean Schwoerer

Mobile 1 425 864-0532

CONFIDENTIAL EMAIL - Work Product - This email is only for use by the intended recipient. If received in error, any use, disclosure, or copying is prohibited. Any inadvertent receipt shall not be a waiver of any privilege or work product protection.

**Comment by bb-Ricardo** [comment] 2022-01-23 23:19
Hi,

That's what I did as well.

I added a random tag to an empty NetBox instance and the started the sync.

**Comment by schwos** [comment] 2022-01-24 00:30
tomorrow ill send you a tag layout that causes it to fail 

Sean Schwoerer

Mobile 1 425 864-0532

CONFIDENTIAL EMAIL - Work Product - This email is only for use by the intended recipient. If received in error, any use, disclosure, or copying is prohibited. Any inadvertent receipt shall not be a waiver of any privilege or work product protection.

**Comment by bb-Ricardo** [comment] 2022-01-24 09:23
great, thank you

**Comment by pn-pn** [comment] 2022-01-24 13:09
Hi, in my case the tags are applied to IP addresses and IP prefixes. Some of the tags were created via API and have custom colors and descriptions that include special characters, e.g. "ó".

I created some of the IP addresses via API and the tags were specified in the request.

Hope that helps.

**Comment by bb-Ricardo** [comment] 2022-01-24 13:35
ok, I will try that. Thank you

**Comment by bb-Ricardo** [comment] 2022-01-25 08:15
I gave it a try but also no issues with a unicode tag
```json
{
    "_mandatory_attrs": [
        "name",
        "api_path",
        "primary_key",
        "data_model"
    ],
    "api_path": "extras/tags",
    "data": {
        "color": "ff5722",
        "created": "2022-01-24",
        "description": "\u00f3\u00f6\u00e4p\u00fcl\u00dcL\u00d6\u00fcd",
        "display": "\u00f3",
        "id": 7,
        "last_updated": "2022-01-24T14:39:43.377306Z",
        "name": "\u00f3",
        "slug": "o",
        "tagged_items": 1,
        "url": "http://netbox.local/api/extras/tags/7/"
    },
    "data_model": {
        "color": 6,
        "description": 200,
        "name": 100,
        "slug": 100
    },
    "deleted": false,
    "is_new": false,
    "name": "tag",
    "nb_id": 7,
    "primary_key": "name",
    "prune": false,
    "source": null,
    "unset_items": [],
    "updated_items": []
}
```
<img width="379" alt="Bildschirmfoto 2022-01-25 um 09 14 38" src="https://user-images.githubusercontent.com/771836/150937751-7a717888-fc71-46c2-9128-3b665b8e96aa.png">

**Comment by bb-Ricardo** [comment] 2022-01-25 08:17
It would be great If someone could offer a remote debug session. This really bugs me, not findig the root cause 😠

**Comment by pn-pn** [comment] 2022-01-25 09:20
I'm afraid I can't be of much help with that because I can't recreate the issue either. The database on my instance is already filled with data and the problem isn't occurring anymore when I run the sync.

Here are some additional details which might be of some help. I looked at the change logs in NetBox.

In my case the last thing the plugin did before throwing an exception is this:

Pre-change data:
```
vrf: null
role: ""
tags: [
    "LAB"
]
status: "reserved"
tenant: 1
address: "XXXX/32"
created: "2022-01-14"
dns_name: ""
nat_inside: null
description: ""
last_updated: "2022-01-17T13:30:56.674Z"
custom_fields: {
    "client_ip": null,
    "hostname": null,
    "owner": "óóó",
    "project": "LAB",
    "service": "LAB",
    "type": null
}
assigned_object_id: null
assigned_object_type: null
```

Post-change data (it changed the netmask and the assigned object type):
```
vrf: null
role: ""
tags: [
    "LAB"
]
status: "reserved"
tenant: 1
address: "XXXX/23"
created: "2022-01-14"
dns_name: ""
nat_inside: null
description: ""
last_updated: "2022-01-17T13:30:56.674Z"
custom_fields: {
    "client_ip": null,
    "hostname": null,
    "owner": "óóó",
    "project": "LAB",
    "service": "LAB",
    "type": null
}
assigned_object_id: null
assigned_object_type: 96
```

Here's how it went:
1. I created a set of tags via API and specified custom colors.
2. I created the IP address object via API and specified the tag more or less like this:
```
{
    "address": line.split(';')[0],
    "tenant": 1,
    "status": "active",
    "tags": [
        {
            "name": "LAB",
            "slug": "lab",
        }
    ],
    "custom_fields": {
        "owner": line.split(';')[1],
        "project": line.split(';')[2],
        "service": line.split(';')[3]
    }
```
3. I modified the tag's color via GUI. This might have been done before I created the IP address object (lost part of the change logs after pruning), but the color is most likely irrelevant anyway. The tag is actually very basic - I'm sorry I wasted your time with the unicode stuff (one custom field assigned to the IP address does have special characters, though):
```
name: "LAB"
slug: "lab"
color: "92a7b1"
created: "2022-01-14"
description: ""
last_updated: "2022-01-14T08:57:13.361Z"
```
4. I ran the plugin. In one of the sources the plugin detected a device that had the same IP address as the one created earlier via API, but it had a different netmask. The API one had /32 and the plugin changed it to /23 and assigned an object type. 

Perhaps the issue occurs when Netbox has a tagged IP address which is a duplicate of one of the addresses stored in the source environment (Vcenter, Napalm)? It was Vcenter in my case.

**Comment by bb-Ricardo** [comment] 2022-01-25 09:46
Thank you for this extensive description. At first glance it doesn't seem related to the issue.

For some reason the Tag, which is retrieved from NetBox is not parsed properly and I wonder when and why this is happening.

looking at this https://github.com/bb-Ricardo/netbox-sync/issues/120#issuecomment-997931170 from @schwos it seems the same tag objects gets "re-added"  to different IP addresses. In memory they are the same object, attached to different objects. And it worked well for the two IP addresses above. 

But especially tags should have been created right at the beginning of the first "sync cycle". An unresolved object is an NetBox object which was created within NetBox sync but is missing it NetBox ID which means it has not been created until that point. This is possible to happen due to dependencies. Example: to assign an IP address to an interface, both instances need to be created first. During creation they get an ID assigned. Once they got an ID netbox-sync can use the interface ID to reference it in "assigned_object_id" for the IP address.

Still confused.

**Comment by pn-pn** [comment] 2022-01-25 11:22
You're right, most of it doesn't seem related to the issue, but have you tested this one scenario - when you create a tagged IP address that's the same as a Vcenter VM IP address and then run netbox-sync for the first time on a completely new Netbox instance, i.e. one that just has the tag and the IP address? If that's not it, then I'm afraid I've run out of ideas. Perhaps schwos will be of more help.

**Comment by pn-pn** [comment] 2022-01-25 13:26
Great news! Good luck fixing it :)

**Comment by bb-Ricardo** [comment] 2022-01-25 18:39
this was done quite quickly, one line.

It was caused by object that returned from NetBox after updating (cause it existed already in NetBox). Then the returned data was added back to the object in line 666. In this case it also had unresolved dependencies (objects not yet created in NetBox) and wanted to add them back to the object (unresolved dependencies get removed from object before its details are sent to NetBox to Create/update it) and hit line 677 where the code tried to parse the tags, which were in this case not turned into an NBTag object and that is why it failed. After adding line 668 it worked because objects get resolved into netbox-sync objects after their details returned from NetBox.
 
https://github.com/bb-Ricardo/netbox-sync/blob/4410d6db8cda8fe4f7b5b0dd1a2cf5faa2ad5e0d/module/netbox/connection.py#L664-L680

Hope this explanation makes any sense.

If anyone is able to verify the fix, that would be amazing.

Thank you

**Comment by MaxFaktor** [comment] 2022-01-27 11:17
> this was done quite quickly, one line.
> 
> It was caused by object that returned from NetBox after updating (cause it existed already in NetBox). Then the returned data was added back to the object in line 666. In this case it also had unresolved dependencies (objects not yet created in NetBox) and wanted to add them back to the object (unresolved dependencies get removed from object before its details are sent to NetBox to Create/update it) and hit line 677 where the code tried to parse the tags, which were in this case not turned into an NBTag object and that is why it failed. After adding line 668 it worked because objects get resolved into netbox-sync objects after their details returned from NetBox.
> 
> https://github.com/bb-Ricardo/netbox-sync/blob/4410d6db8cda8fe4f7b5b0dd1a2cf5faa2ad5e0d/module/netbox/connection.py#L664-L680
> 
> Hope this explanation makes any sense.
> 
> If anyone is able to verify the fix, that would be amazing.
> 
> Thank you

I have the same problem. After some testing, I deleted my site and all VMs, tried to run the script again and got the same error.
I added changes to the connection.py script and it worked! Many thanks!

**Comment by bb-Ricardo** [comment] 2022-01-27 17:22
great, than I consider this issue as resolved 🥳

**Comment by juliouzzzz** [comment] 2022-03-11 15:27
Hello,

I've still same error.
```
2022-03-11 12:03:15,197 - INFO: Virtual machine interface 'vNIC 1 (VM-DMZ-INTERNE) (BLABLABLA)' attribute 'enabled' changed from 'True' to 'False'
Traceback (most recent call last):
  File "/data/netbox-sync/netbox-sync.py", line 145, in <module>
    main()
  File "/data/netbox-sync/netbox-sync.py", line 124, in main
    inventory.tag_all_the_things(nb_handler)
  File "/data/netbox-sync/module/netbox/inventory.py", line 299, in tag_all_the_things
    if bool(set(this_object.get_tags()).intersection(self.source_tags_of_disabled_sources)) is True:
  File "/data/netbox-sync/module/netbox/object_classes.py", line 757, in get_tags
    return [x.get_display_name() for x in self.data.get("tags", list())]
  File "/data/netbox-sync/module/netbox/object_classes.py", line 757, in <listcomp>
    return [x.get_display_name() for x in self.data.get("tags", list())]
AttributeError: 'dict' object has no attribute 'get_display_name'
```
I've read your analysis.
I tried to delete some tags, some netbox-sync tags, etc etc but i can't RAZ everything.

I tried to disable 1vcenter (one source) but same problem :
```
2022-03-11 15:40:40,031 - DEBUG2: Object '43 (192.168.43.0/29 - xxxx)' was added from a currently disabled source. Skipping orphaned tagging.
2022-03-11 15:40:40,032 - DEBUG2: Object '58 (192.168.99.x)' was added from a currently disabled source. Skipping orphaned tagging.
2022-03-11 15:40:40,032 - DEBUG2: Object '88 (YYYYY)' was added from a currently disabled source. Skipping orphaned tagging.
Traceback (most recent call last):
  File "/data/netbox-sync/netbox-sync.py", line 145, in <module>
    main()
  File "/data/netbox-sync/netbox-sync.py", line 124, in main
    inventory.tag_all_the_things(nb_handler)
  File "/data/netbox-sync/module/netbox/inventory.py", line 299, in tag_all_the_things
    if bool(set(this_object.get_tags()).intersection(self.source_tags_of_disabled_sources)) is True:
  File "/data/netbox-sync/module/netbox/object_classes.py", line 757, in get_tags
    return [x.get_display_name() for x in self.data.get("tags", list())]
  File "/data/netbox-sync/module/netbox/object_classes.py", line 757, in <listcomp>
    return [x.get_display_name() for x in self.data.get("tags", list())]
AttributeError: 'dict' object has no attribute 'get_display_name'
```

Do you have a way to find which object (tag, custom_field, interface,... ) is the problem ?

I really like this sync plugin and i loose this sync 2 month ago.

Thank you in advance

**Comment by bb-Ricardo** [comment] 2022-03-11 15:41
Hi,

This is not meant to happen. Which version are you using?

**Comment by juliouzzzz** [comment] 2022-03-11 15:43
Hi,
I use the last netbox-sync version and v3.1.1 of netbox

**Comment by bb-Ricardo** [comment] 2022-03-11 15:59
MMhhhh, I guess I have to take another look. Sorry for that.

can you run the script with `-l DEBUG2` and post the last 30 lines here?

Thank you.

**Comment by juliouzzzz** [comment] 2022-03-11 17:05
```
2022-03-11 17:14:17,598 - DEBUG: Parsing vCenter VM: BDDPG02LV
2022-03-11 17:14:17,784 - DEBUG2: Found default IPv4 gateway 10.60.1.254
2022-03-11 17:14:17,784 - DEBUG2: Parsing device VirtualVmxnet3: 00:50:56:8C:DC:47
2022-03-11 17:14:17,793 - DEBUG2: Trying to find a virtual machine based on the collected name, cluster, IP and MAC addresses
2022-03-11 17:14:17,877 - DEBUG2: Found a exact matching virtual machine object: BDDPG02LV(Cluster B - DMZ INT)
2022-03-11 17:14:17,877 - DEBUG2: Found a matching virtual machine object: BDDPG02LV(Cluster B - DMZ INT)
2022-03-11 17:14:17,878 - DEBUG2: Parsing 'virtual machine' data structure: BDDPG02LV
2022-03-11 17:14:17,878 - DEBUG2: Parsing 'cluster' data structure: Cluster B - DMZ INT
2022-03-11 17:14:17,878 - DEBUG2: Parsing 'platform' data structure: Red Hat Enterprise Linux 7 (64-bit)
2022-03-11 17:14:17,878 - INFO: Virtual machine 'RMMBDDPG02LV' attribute 'status' changed from 'active' to 'offline'
2022-03-11 17:14:17,879 - DEBUG: Updated virtual machine object: BDDPG02LV
2022-03-11 17:14:17,879 - DEBUG2: Found a matching vm_role_relation 'VMserver' (.*) for BDDPG02LV.
2022-03-11 17:14:17,879 - DEBUG2: Parsing 'virtual machine' data structure: BDDPG02LV
2022-03-11 17:14:17,879 - DEBUG2: Parsing 'device role' data structure: VMserver
2022-03-11 17:14:17,879 - DEBUG2: Trying to match current object interfaces in NetBox with discovered interfaces
2022-03-11 17:14:17,885 - DEBUG2: Found '2' NICs in NetBox for 'BDDPG02LV'
2022-03-11 17:14:17,885 - DEBUG2: Found 1:1 name match for NIC 'vNIC 1 (VM-DMZ-INTERNE)'
2022-03-11 17:14:17,886 - DEBUG2: Parsing 'virtual machine interface' data structure: vNIC 1 (VM-DMZ-INTERNE) (RMMBDDPG02LV)
2022-03-11 17:14:17,886 - INFO: Virtual machine interface 'vNIC 1 (VM-DMZ-INTERNE) (BDDPG02LV)' attribute 'enabled' changed from 'True' to 'False'
2022-03-11 17:14:17,887 - DEBUG: Updated virtual machine interface object: vNIC 1 (VM-DMZ-INTERNE) (BDDPG02LV)
2022-03-11 17:14:17,893 - DEBUG2: Parsing 'tag' data structure: Source: vcenter
2022-03-11 17:14:17,893 - DEBUG2: Parsing 'device role' data structure: Server
Traceback (most recent call last):
  File "/data/netbox-sync/netbox-sync.py", line 145, in <module>
    main()
  File "/data/netbox-sync/netbox-sync.py", line 124, in main
    inventory.tag_all_the_things(nb_handler)
  File "/data/netbox-sync/module/netbox/inventory.py", line 299, in tag_all_the_things
    if bool(set(this_object.get_tags()).intersection(self.source_tags_of_disabled_sources)) is True:
  File "/data/netbox-sync/module/netbox/object_classes.py", line 757, in get_tags
    return [x.get_display_name() for x in self.data.get("tags", list())]
  File "/data/netbox-sync/module/netbox/object_classes.py", line 757, in <listcomp>
    return [x.get_display_name() for x in self.data.get("tags", list())]
AttributeError: 'dict' object has no attribute 'get_display_name'
```

**Comment by juliouzzzz** [comment] 2022-03-15 13:28
Hi,
May i have to open new issue ?

Thanks

**Comment by bb-Ricardo** [comment] 2022-03-15 13:32
Not really, Just reuse this one.

**Comment by juliouzzzz** [comment] 2022-03-15 14:34
No worries.
Thanks for reopen ;)

**Comment by Sivolen** [comment] 2022-03-29 22:18
After changed i have a new error:

```
Traceback (most recent call last):
  File "./netbox-sync.py", line 145, in <module>
    main()
  File "./netbox-sync.py", line 138, in main
    nb_handler.prune_data()
  File "/opt/scripts/netbox-sync/module/netbox/connection.py", line 812, in prune_data
    ret = self.request(nb_object_sub_class, req_type="DELETE", nb_id=this_object.nb_id)
  File "/opt/scripts/netbox-sync/module/netbox/connection.py", line 288, in request
    result = response.json()
  File "/home/a.gridnev/.local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Sivolen** [comment] 2022-03-31 04:31
Hm, after update netbox up to version 3.1.10, problem has gone.

**Comment by juliouzzzz** [comment] 2022-03-31 08:05
Hi,
It works perfect for me on first run without the option "sync_custom_attributes" : 2022-03-31 09:54:22,272 - INFO: Completed NetBox Sync
But after this i turned this option to "True", and i had some tags who "are not an NetBox objet" like you mention in your code.

So i update this issue #120 : 
```
2022-03-31 09:59:24,538 - ERROR: This tag is not an NetBox object: {'id': 30, 'url': 'https://cmdb.geg.loc/api/extras/tags/30/', 'display': 'Borne', 'name': 'Borne', 'slug': 'borne', 'color': 'c0c0c0'}
2022-03-31 09:59:24,538 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
2022-03-31 09:59:24,538 - ERROR: This tag is not an NetBox object: {'id': 30, 'url': 'https://cmdb.geg.loc/api/extras/tags/30/', 'display': 'Borne', 'name': 'Borne', 'slug': 'borne', 'color': 'c0c0c0'}
2022-03-31 09:59:24,538 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
2022-03-31 09:59:24,538 - ERROR: This tag is not an NetBox object: {'id': 30, 'url': 'https://cmdb.geg.loc/api/extras/tags/30/', 'display': 'Borne', 'name': 'Borne', 'slug': 'borne', 'color': 'c0c0c0'}
```
Should i update to the last 3.1 : 3.1.10?

Many thanks for the time on this issue !

Regards

**Comment by bb-Ricardo** [comment] 2022-03-31 15:31
Not sure if you should update to the latest version. I don't know your environment.
And there are no warnings or errors earlier in the log?

**Comment by Houtek** [comment] 2022-04-06 14:08
Hi,
after an update to Netbox v3.1.10, I do receive this error too.
We have some tags which are added with ansible to Netbox and which aren't configured in the vCenter.

`2022-04-06 14:43:21,008 - ERROR: This tag is not an NetBox object: {'id': 21, 'url': 'https://netbox.internal.domain/api/extras/tags/21/', 'display': 'linux', 'name': 'linux', 'slug': 'linux', 'color': 'cddc39'}
2022-04-06 14:43:21,008 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
2022-04-06 14:43:21,008 - ERROR: This tag is not an NetBox object: {'id': 21, 'url': 'https://netbox.internal.domain/api/extras/tags/21/', 'display': 'linux', 'name': 'linux', 'slug': 'linux', 'color': 'cddc39'}
2022-04-06 14:43:21,008 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
2022-04-06 14:43:21,008 - ERROR: This tag is not an NetBox object: {'id': 21, 'url': 'https://netbox.internal.domain/api/extras/tags/21/', 'display': 'linux', 'name': 'linux', 'slug': 'linux', 'color': 'cddc39'}
2022-04-06 14:43:21,009 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
2022-04-06 14:43:21,009 - ERROR: This tag is not an NetBox object: {'id': 21, 'url': 'https://netbox.internal.domain/api/extras/tags/21/', 'display': 'linux', 'name': 'linux', 'slug': 'linux', 'color': 'cddc39'}
2022-04-06 14:43:21,009 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
2022-04-06 14:43:21,009 - ERROR: This tag is not an NetBox object: {'id': 21, 'url': 'https://netbox.internal.domain/api/extras/tags/21/', 'display': 'linux', 'name': 'linux', 'slug': 'linux', 'color': 'cddc39'}
2022-04-06 14:43:21,009 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
2022-04-06 14:43:21,009 - ERROR: This tag is not an NetBox object: {'id': 21, 'url': 'https://netbox.internal.domain/api/extras/tags/21/', 'display': 'linux', 'name': 'linux', 'slug': 'linux', 'color': 'cddc39'}
2022-04-06 14:43:21,010 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
2022-04-06 14:43:21,010 - ERROR: This tag is not an NetBox object: {'id': 21, 'url': 'https://netbox.internal.domain/api/extras/tags/21/', 'display': 'linux', 'name': 'linux', 'slug': 'linux', 'color': 'cddc39'}
2022-04-06 14:43:21,010 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
2022-04-06 14:43:21,010 - ERROR: This tag is not an NetBox object: {'id': 21, 'url': 'https://netbox.internal.domain/api/extras/tags/21/', 'display': 'linux', 'name': 'linux', 'slug': 'linux', 'color': 'cddc39'}
2022-04-06 14:43:21,010 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
2022-04-06 14:43:21,010 - ERROR: This tag is not an NetBox object: {'id': 21, 'url': 'https://netbox.internal.domain/api/extras/tags/21/', 'display': 'linux', 'name': 'linux', 'slug': 'linux', 'color': 'cddc39'}
2022-04-06 14:43:21,011 - ERROR: Please report this here: https://github.com/bb-Ricardo/netbox-sync/issues/120
`

Regards

**Comment by bb-Ricardo** [comment] 2022-04-07 22:02
Thank you all for your help and patients. I'm positiv I narrowed down the issue. I was able to trigger it in my test env.

**Comment by bb-Ricardo** [comment] 2022-04-07 22:45
The Issue was that NetBox recently (3.1.0) added tags to organisational objects. This was not reflected in the data model of each object. and `get_tags()` only checked if there was tag data present without consulting the model first.

On the other hand: When objects are read and parsed, only data in the data model was looked at and the rest was ignored. This way the tags assigned to these objects were never converted into an internal object and a parsing of this data eventually failed.

Can you please check out the latest `development` branch and see if it fixes the issue.

Just saw that NetBox 3.2.0 has been release three days ago. 😅

**Closed** 2022-04-09 22:18 UTC
