### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'get_display_name'

### ISSUE THREAD

**Issue by Sivolen** [bb-Ricardo/netbox-sync#161] opened 2022-03-29 05:30 UTC
Hi!
I have an error, how i can fix it ?
Debug log in atach
```
Traceback (most recent call last):
  File "./netbox-sync.py", line 145, in <module>
    main()
  File "./netbox-sync.py", line 124, in main
    inventory.tag_all_the_things(nb_handler)
  File "/opt/scripts/netbox-sync/module/netbox/inventory.py", line 299, in tag_all_the_things
    if bool(set(this_object.get_tags()).intersection(self.source_tags_of_disabled_sources)) is True:
  File "/opt/scripts/netbox-sync/module/netbox/object_classes.py", line 757, in get_tags
    return [x.get_display_name() for x in self.data.get("tags", list())]
  File "/opt/scripts/netbox-sync/module/netbox/object_classes.py", line 757, in <listcomp>
    return [x.get_display_name() for x in self.data.get("tags", list())]
AttributeError: 'dict' object has no attribute 'get_display_name'

```
[debug.log](https://github.com/bb-Ricardo/netbox-sync/files/8368319/debug.log)

**Comment by bb-Ricardo** [comment] 2022-03-29 06:36
Thank you for the info and the debug log. Seems to be a duplicate of #120

**Comment by bb-Ricardo** [comment] 2022-03-29 14:59
Closing this as duplicate, please see #120 for this. Also just pushed a commit to ease up debugging

**Closed by bb-Ricardo** 2022-03-29 14:59 UTC
