### ISSUE TITLE
FR: add reading of ENV vars for configuration

### ISSUE THREAD

**Issue by nikolasj** [bb-Ricardo/netbox-sync#227] opened 2022-09-13 12:11 UTC
Can the sync plugin get authorization data from vault or environment variables?
Maybe in settings.ini 
```
api_token = $API_TOKEN_NETBOX
[source/my-vcenter-example]
username = $USERNAME
password = $PASSWORD
```

**Comment by bb-Ricardo** [comment] 2022-09-13 12:22
Hi,

I had this idea in mind for a long time. Also a more general approach to support all variables would be great.
The issue is the naming of according vars.

example for NetBox vars would be fairly easy:
```
NBS_NETBOX_API_TOKEN=
```

with sources not so easy. I only came up with two approaches.

first:
```
NBS_SOURCE_my-vcenter-example_USERNAME
```
But this would limit the possible characters for source names. Also we need to parsing of available vars first


Second idea is to enumerate sources:
```
NBS_SOURCE_1_NAME=my-vcenter-example
NBS_SOURCE_1_TYPE=vmware
NBS_SOURCE_1_USERNAME=readonlyuser
```
This is also not very intuitive.

Any ideas/suggestions/recommendations?

**Comment by nikolasj** [comment] 2022-09-13 12:55
I think the second option is easier. I think if described in the documentation there will be no big problems.
To make it clearer, you can make it mandatory to indicate the order in the sort. 
For example,
```
[source-1/my-vcenter-1]
...

[source-2/my-vcenter-2]
...
```

This functionality would be very useful for me.

**Comment by bb-Ricardo** [comment] 2022-09-13 16:09
Hey, this would imply that every user has to change their config without a direct benefit for everyone. This is not possible. There must be a different way.

**Comment by nikolasj** [comment] 2022-09-14 07:42
Then I think the first option is better.
>But this would limit the possible characters for source names

I don't think this is a problem. The documentation can describe naming examples. If the name does not match, then it is expected that all parameters are specified only in the config

I think the most important thing is to hide the passwords and the token. Other parameters can be left in the config.
```
NBS_NETBOX_API_TOKEN=<token>
NBS_SOURCE_my-vcenter-example_PASSWORD=<password>
```
What do you think about it?

**Comment by bb-Ricardo** [comment] 2023-02-14 09:45
This will be part of the next version.

Did a complete rewrite of config parsing.

Config types supported:
* INI files
* YAML files
* Environment variables

Just the documentation part is still left.

**Comment by bb-Ricardo** [comment] 2023-02-14 15:07
Would you be able to try out "feature/improved-config-parsing" branch?

**Comment by bb-Ricardo** [comment] 2023-02-17 20:40
Hey @nikolasj,

I just finished the documentation. You can find it here:
https://github.com/bb-Ricardo/netbox-sync/blob/development/README.md#configuration

it is now merged to the `development` branch. Would you mind to try it out?

thank you.

**Comment by bb-Ricardo** [comment] 2023-02-24 10:02
@nikolasj did you have any chance to test this?

**Closed** 2023-03-20 14:55 UTC
Labels: enhancement
