### ISSUE TITLE
netbox-sync removes and adds the same data without changes

### ISSUE THREAD

**Issue by cfrietschy** [bb-Ricardo/netbox-sync#245] opened 2022-10-11 13:27 UTC
netbox-sync changes the "Untagged VLAN" field of the vmk ports for ESXi hosts on each run. During a run, the VLAN is entered. On the next run it is removed again and so on.
This leads to a lot of changes in the changelog. I am sure that no changes have been made to the vCenter or ESXi host between each sync.

first run:
```
2022-10-10 13:39:01,689 - DEBUG2: Trying to find prefix for IP: 10.13.4.12/16
2022-10-10 13:39:01,698 - DEBUG2: Found IP '10.13.4.12/16' matches global prefix '10.13.0.0/16'
2022-10-10 13:39:01,731 - DEBUG2: Found existing NetBox IP address object: 10.13.4.12/16
2022-10-10 13:39:01,731 - DEBUG2: Parsing 'IP address' data structure: 10.13.4.12/16
2022-10-10 13:39:01,731 - DEBUG2: Found matching prefix VLAN 24 (DC-01) for untagged interface VLAN.
2022-10-10 13:39:01,732 - DEBUG2: Parsing 'interface' data structure: vmk0 (tstesx201.b00.dc01b.example.com)
2022-10-10 13:39:01,732 - INFO: Interface 'vmk0 (tstesx201.b00.dc01b.example.com)' attribute 'untagged_vlan' changed from 'None' to '24 (DC-01)'
2022-10-10 13:39:01,732 - DEBUG: Updated interface object: vmk0 (tstesx201.b00.dc01b.example.com)
2022-10-10 13:39:01,732 - DEBUG2: Parsing 'interface' data structure: vmk1 (tstesx201.b00.dc01b.example.com)
2022-10-10 13:39:01,732 - DEBUG2: Trying to find prefix for IP: 10.240.0.166/16
2022-10-10 13:39:01,741 - DEBUG2: Found IP '10.240.0.166/16' matches global prefix '10.240.0.0/24'
2022-10-10 13:39:01,747 - DEBUG2: Found existing NetBox IP address object: 10.240.0.166/16
2022-10-10 13:39:01,747 - DEBUG2: Parsing 'IP address' data structure: 10.240.0.166/16
2022-10-10 13:39:01,747 - DEBUG2: Found matching prefix VLAN 4 (vMotion) for untagged interface VLAN.
2022-10-10 13:39:01,747 - DEBUG2: Parsing 'interface' data structure: vmk1 (tstesx201.b00.dc01b.example.com)
2022-10-10 13:39:01,747 - INFO: Interface 'vmk1 (tstesx201.b00.dc01b.example.com)' attribute 'untagged_vlan' changed from 'None' to '4 (vMotion)'
2022-10-10 13:39:01,747 - DEBUG: Updated interface object: vmk1 (tstesx201.b00.dc01b.example.com)
```

second run:
```
2022-10-10 13:58:53,936 - INFO: Setting attribute 'untagged_vlan' for 'vmk0 (tstesx201.b00.dc01b.example.com)' to None
2022-10-10 13:58:53,936 - DEBUG2: Trying to find prefix for IP: 10.13.4.12/16
2022-10-10 13:58:53,945 - DEBUG2: Found IP '10.13.4.12/16' matches global prefix '10.13.0.0/16'
2022-10-10 13:58:53,978 - DEBUG2: Found existing NetBox IP address object: 10.13.4.12/16
2022-10-10 13:58:53,978 - DEBUG2: Parsing 'IP address' data structure: 10.13.4.12/16
2022-10-10 13:58:53,978 - DEBUG2: Found matching prefix VLAN 24 (DC-01) for untagged interface VLAN.
2022-10-10 13:58:53,979 - DEBUG2: Parsing 'interface' data structure: vmk0 (tstesx201.b00.dc01b.example.com)
2022-10-10 13:58:53,979 - DEBUG2: Parsing 'interface' data structure: vmk1 (tstesx201.b00.dc01b.example.com)
2022-10-10 13:58:53,979 - INFO: Setting attribute 'untagged_vlan' for 'vmk1 (tstesx201.b00.dc01b.example.com)' to None
2022-10-10 13:58:53,979 - DEBUG2: Trying to find prefix for IP: 10.240.0.166/16
2022-10-10 13:58:53,988 - DEBUG2: Found IP '10.240.0.166/16' matches global prefix '10.240.0.0/24'
2022-10-10 13:58:53,994 - DEBUG2: Found existing NetBox IP address object: 10.240.0.166/16
2022-10-10 13:58:53,994 - DEBUG2: Parsing 'IP address' data structure: 10.240.0.166/16
2022-10-10 13:58:53,994 - DEBUG2: Found matching prefix VLAN 4 (vMotion) for untagged interface VLAN.
2022-10-10 13:58:53,995 - DEBUG2: Parsing 'interface' data structure: vmk1 (tstesx201.b00.dc01b.example.com)
```

**Comment by bb-Ricardo** [comment] 2022-12-27 23:36
Hi @cfrietschy,

apologies for not even commenting on your bug report. This should not happen. I will have a look into it.

**Comment by bb-Ricardo** [comment] 2023-01-13 18:01
Hey,

I'm trying to fix this bug but unsure how to investigate it probably and need your help 😃.

Would you be able to run the script with a host_include_filter set to this particular host where this is happening? I would need the output of `-l DEBUG3` redirected to a file.

Then two or three runs where this behavior is observable. That should definitely cover it and then I would be able to debug it easily.

Thank you very much.

**Comment by cfrietschy** [comment] 2023-01-13 21:47
Which part of the log do you need exactly? I run it 3 times and the log is 238M in size. :)

**Comment by bb-Ricardo** [comment] 2023-01-13 22:15
Wow, that's great. I know it's huge. If you tar.gz it it should get quite a bit smaller. You could send it to my mail address here:

https://github.com/bb-Ricardo/fritzinfluxdb/blob/468d3900dc08920257be22c0871531ed941579f7/fritzinfluxdb.py#L32

**Comment by bb-Ricardo** [comment] 2023-01-17 16:32
Hey, just wondering. Did you already send the logs? Haven't received anything, so was just curious.

**Comment by cfrietschy** [comment] 2023-01-18 19:26
> Hey, just wondering. Did you already send the logs? Haven't received anything, so was just curious.

No, I have not sent the logs yet. Unfortunately, I have to anonymize the data first. Otherwise I can't send them to you. I haven't had time to do that yet.

**Comment by bb-Ricardo** [comment] 2023-01-19 20:11
Well if it helps, I would just need all the log lines of the host parsing part including the output from the VMWare API.

**Comment by rizlas** [comment] 2023-02-14 07:37
Hi,
I tried to replicate this with a clean instance of NetBox and only one source, with the target of reducing the log file size. Unfortunately I was unable to reproduce this.
Log files contains too many sensitive information to be shared.

How can we tackle this?

**Comment by bb-Ricardo** [comment] 2023-04-20 18:51
any updates? would a remote session be possible?

**Comment by bb-Ricardo** [comment] 2023-06-02 13:52
Hey,

Thank you for looking into this. This is definitely a possibility and I already have an idea of how to mitigate this.
Would need to keep the original attribute content until the end and drop attributes from syncing if current content and original content are the same.

**Comment by sHorst** [comment] 2023-06-02 19:16
And for the "which component is the right value" problem, you could just add to the documentation, that the last source will overwrite those. Or better make it configurable, which source will be the "true source"

**Comment by bb-Ricardo** [comment] 2023-06-05 20:11
Hey @sHorst @rizlas @cfrietschy,

I just pushed a new commit to the `development` branch. Would you be able to test if this fixes the observed behaviour?

Thank you

**Comment by sHorst** [comment] 2023-06-06 13:01
hey, it fixes the issue, only the first element will set the field .. in the default configuration (order vcenter/redfish) this leads to no description in netbox. It would be better to have it the other way around, but it fixes the problem.

**Comment by bb-Ricardo** [comment] 2023-06-06 13:46
The last source should set the final attribute value.

At least thats how it is implemented.

**Comment by sHorst** [comment] 2023-06-06 19:19
correct, thought the description was comming from the other source .. but my point stands, that in the default, it will lead to the description net beeing set, for interfaces, since the redfish import will set it to '', the vcenter will set it to the connected vSwitch.

**Comment by francesco-noc** [comment] 2023-06-13 14:36
Hi, we are experiencing the same behaviour. When we set "disable_vlan_sync" to "False", NetBox Sync changes the vlan assigned to the vNICs each time it runs. The first time it sets the vlan to None, the second time it sets the vlan to the correct value, the third time it sets the vlan to None, the fourth time it sets the vlan to the correct value, and so on. Always without making any changes to NetBox or vCenter. 
All retrieved vlans are already present in Netbox.
When "disable_vlan_sync" is "True" the problem does not occur.
We also tried with the development branch but the behaviour is the same.
The DEBUG log is very verbose and full of sensitive data, which line are you interested in? Anonymising it is very laborious.
Thank you

**Comment by sHorst** [comment] 2023-06-13 16:59
Did you try to reorder the sorces in the config file? The last one sets the value, even though the log will tell you the intermediate value.

**Comment by bb-Ricardo** [comment] 2023-06-13 18:33
> Hi, we are experiencing the same behaviour. When we set "disable_vlan_sync" to "False", NetBox Sync changes the vlan assigned to the vNICs each time it runs. The first time it sets the vlan to None, the second time it sets the vlan to the correct value, the third time it sets the vlan to None, the fourth time it sets the vlan to the correct value, and so on. Always without making any changes to NetBox or vCenter. 
> 
> All retrieved vlans are already present in Netbox.
> 
> When "disable_vlan_sync" is "True" the problem does not occur.
> 
> We also tried with the development branch but the behaviour is the same.
> 
> The DEBUG log is very verbose and full of sensitive data, which line are you interested in? Anonymising it is very laborious.
> 
> Thank you

How many sources are you using in your configuration?

**Comment by rizlas** [comment] 2023-06-14 07:33
Still happening in dev branch.

My config is:

One source in config file

```
disable_vlan_sync = True
ignore_unknown_source_object_pruning = true
```

![first](https://github.com/bb-Ricardo/netbox-sync/assets/8522635/e7222009-21bc-4cf2-8228-16dff347e48e)
![second](https://github.com/bb-Ricardo/netbox-sync/assets/8522635/e231fa11-360f-4800-b756-57031dcb65e3)

**Comment by bb-Ricardo** [comment] 2023-06-14 07:51
Yes, this seems to be a different issue. Then one which got fix definitely stemmed feom having more then one source and the same attribute gets overwritten.

@rizlas A short online debug session?

**Comment by rizlas** [comment] 2023-06-14 10:38
Mail incoming

**Comment by bb-Ricardo** [comment] 2023-06-15 19:10
@rizlas Do you have vlan_sync enabled or disabled? From our conversation I remember you disabled it a few month ago. Just wanted to be sure.

**Comment by rizlas** [comment] 2023-06-15 19:20
Yes it is disabled

**Comment by bb-Ricardo** [comment] 2023-06-15 20:11
This seems to be the issue. Just for testing purposes would you be able to enable this option again and try to sync a few times and see if it still occurs?

exactly what @francesco-noc described in his https://github.com/bb-Ricardo/netbox-sync/issues/245#issuecomment-1589442477

**Comment by bb-Ricardo** [comment] 2023-06-15 21:12
Hey @rizlas, @francesco-noc,

I just pushed a fix to the "fix/disable-vlan-sync-option-#245" branch. Would you be able to checkout this branch and run a few tests?

Thank you.

**Comment by rizlas** [comment] 2023-06-16 08:24
Yeah 🙌🏻 this is it. My side it is fixed for both hosts and vms virtual interfaces.

**Comment by bb-Ricardo** [comment] 2023-06-16 08:33
I have to run a few additional tests but it should work now.

**Comment by rizlas** [comment] 2023-06-16 09:17
Same behavior with `disable_vlan_sync = False`

**Comment by bb-Ricardo** [comment] 2023-06-19 21:18
Awesome, thank you for the feedback. Probably gonna be a 1.5.0

**Closed** 2023-06-19 21:18 UTC
Labels: bug, awaiting reply
