### ISSUE TITLE
DNS resolution fails when any FHRP groups exist within netbox

### ISSUE THREAD

**Issue by dirtycache** [bb-Ricardo/netbox-sync#144] opened 2022-02-09 23:30 UTC
```
2022-02-08 19:20:04,621 - DEBUG: Start resolving relations
2022-02-08 19:20:04,653 - ERROR: Attribute 'assigned_object_type' for '204.27.195.254/24' invalid: ipam.fhrpgroup

```

If the FHRP groups are removed, sync proceeds as expected.

Netbox v3.1.6

**Comment by bb-Ricardo** [comment] 2022-04-07 21:29
Thank you for this finding. This is a duplicate of #137 and should already be fixed in the `development` branch. Can you please test it out?

**Closed by bb-Ricardo** 2022-04-07 21:29 UTC
Labels: bug
